source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TCBlobDownloadObjC_Example', :exclusive => true do
  pod "TCBlobDownloadObjC", :path => "../"
end

target 'TCBlobDownloadObjC_Tests', :exclusive => true do
  pod "TCBlobDownloadObjC", :path => "../"

  
end
